Escape % characthers in help strings to correct --help (#151)
Avoids errors such as

Traceback (most recent call last):
  File "/Users/ska/projects/others/tesla_dashcam/tesla_dashcam/tesla_dashcam.py", line 3949, in <module>
    sys.exit(main())
  File "/Users/ska/projects/others/tesla_dashcam/tesla_dashcam/tesla_dashcam.py", line 3247, in main
    args = parser.parse_args()
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1818, in parse_args
    args, argv = self.parse_known_args(args, namespace)
[...]
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 530, in _format_action
    help_text = self._expand_help(action)
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 626, in _expand_help
    return self._get_help_string(action) % params
TypeError: %x format: an integer is required, not dict

when running with --help.